version: '2'
services:
  zk:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.222
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.222:2181
    links:
      - zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "29000:9000"
    environment:
      ZK_HOSTS: zk:2181
    links:
      - kafka
      - zk
    depends_on:
      - kafka
